INSERT INTO DEPARTMENT (DEPT_ID, DEPT_NAME) VALUES (1, 'IT');
INSERT INTO DEPARTMENT (DEPT_ID, DEPT_NAME) VALUES (2, 'HR');
INSERT INTO DEPARTMENT (DEPT_ID, DEPT_NAME) VALUES (3, 'Sales');
INSERT INTO DEPARTMENT (DEPT_ID, DEPT_NAME) VALUES (4, 'Marketing');
