
INSERT INTO DEPARTMENT (DEPT_ID, DEPT_NAME) VALUES (1, 'IT');
INSERT INTO DEPARTMENT (DEPT_ID, DEPT_NAME) VALUES (2, 'HR');
INSERT INTO DEPARTMENT (DEPT_ID, DEPT_NAME) VALUES (3, 'Sales');
INSERT INTO DEPARTMENT (DEPT_ID, DEPT_NAME) VALUES (4, 'Marketing');

INSERT INTO EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, DEPT_ID) VALUES (1, 'Foo', 'Bar', 'foo.bar@gmail.com', 1);
INSERT INTO EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, DEPT_ID) VALUES (2, 'James', 'Smith', 'James@gmail.com', 1);
INSERT INTO EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, DEPT_ID) VALUES (3, 'Robert', 'Johnson', 'Robert@gmail.com', 1);
INSERT INTO EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, DEPT_ID) VALUES (4, 'John', 'Williams', 'John@gmail.com', 1);

INSERT INTO EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, DEPT_ID) VALUES (5, 'Michael', 'Brown', 'Michael@gmail.com', 2);
INSERT INTO EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, DEPT_ID) VALUES (6, 'David', 'Jones', 'David@gmail.com', 2);

INSERT INTO EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, DEPT_ID) VALUES (7, 'William', 'Garcia', 'William@gmail.com', 3);
INSERT INTO EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, DEPT_ID) VALUES (8, 'Richard', 'Miller', 'Richard@gmail.com', 3);
INSERT INTO EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, DEPT_ID) VALUES (9, 'Joseph', 'Davis', 'Joseph@gmail.com', 3);

INSERT INTO EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, DEPT_ID) VALUES (10, 'Thomas', 'Wilson', 'Thomas@gmail.com', 4);
INSERT INTO EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, DEPT_ID) VALUES (11, 'Charles', 'Anderson', 'Charles@gmail.com', 4);
INSERT INTO EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, DEPT_ID) VALUES (12, 'Christopher', 'Moore', 'Christopher@gmail.com', 4);



